### ISSUE TITLE
El método debe ser asíncrono y falta el tipo de dato Task

### ISSUE THREAD

**Issue by DjMarte** [enelramon/DemoPrioridades#1]
https://github.com/enelramon/DemoPrioridades/blob/7f059b8254fa909a1eae48d2e7a0dc2ff3d5928c/RegistroPrioridades/Services/PrioridadService.cs#L60

**Comment by enelramon** [comment]
Efectivamente no esta asíncrono, pero fíjate que no estoy llamando ToListAsync().
Procederé a cambiar el método y la implementación.

**Comment by enelramon** [comment]
Efectivamente no esta asíncrono, pero fijate que no estoy llamando ToListAsync().
Procederé a cambiar el método y la implementación.
